@RestaurantApi_HostAddress = http://localhost:5243
@RestaurantId = 844

GET {{RestaurantApi_HostAddress}}/api/restaurant
Accept: application/json

###

GET {{RestaurantApi_HostAddress}}/api/restaurant/{{RestaurantId}}
Accept: application/json

###
POST {{RestaurantApi_HostAddress}}/api/restaurant
Content-Type: application/json
{
    "name": "PizzeriaPizzeriaPizzeriaPizzeriaPizzeriaPizzeriaPizzeriaPizzeriaPizzeria ",
    "description": "Najlepsza pizza w mieœcie!",
    "category": "Pizza",
    "hasDelivery": true,
    "contactEmail": "kontakt@pizzerianapoli.pl",
    "contactNumber": "+48123456789",
    "city": "Warszawa",
    "street": "Ulica Pizza 12",
    "postalCode": "00-001"
}

###

DELETE {{RestaurantApi_HostAddress}}/api/restaurant/{{RestaurantId}}
Accept: application/json

###
PUT {{RestaurantApi_HostAddress}}/api/restaurant/{{RestaurantId}}
Content-Type: application/json
{
    "name": "Update Test",
    "description": "Update Test Description",
    "hasDelivery": false
}